version: "2"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto/mosquitto-default.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/certs:/mosquitto/certs
    ports:
      - 1883:1883
      - 8883:8883
      - 1884:1884
      - 8884:8884
    restart: unless-stopped

  mosquitto-authenticated:
    image: eclipse-mosquitto
    container_name: mosquitto-authenticated
    volumes:
      - ./mosquitto/mosquitto-authenticated.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto-authenticated-passwd:/mosquitto/mosquitto-authenticated-passwd
    ports:
      - 1885:1885
    restart: unless-stopped

  mosquitto-limited:
    image: eclipse-mosquitto
    container_name: mosquitto-limited
    volumes:
      - ./mosquitto/mosquitto-limited.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1886:1886
    restart: unless-stopped
