version: "2"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./Docker/certs:/mosquitto/data/certs
      - ./Docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 8883:8883
      - 1884:1884
      - 8884:8884
    restart: unless-stopped

  mosquitto-authenticated:
    image: eclipse-mosquitto
    container_name: mosquitto-authenticated
    volumes:
      - ./Docker/mosquitto-authenticated/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./Docker/mosquitto-authenticated/passwd:/mosquitto/config/passwd
    ports:
      - 1885:1883
    restart: unless-stopped
    
  mosquitto-limited:
    image: eclipse-mosquitto
    container_name: mosquitto-limited
    volumes:
      - ./Docker/mosquitto-limited/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1886:1883
    restart: unless-stopped
